---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
How doth the little crocodile 

Improve his shining tail,

And pour the waters of the Nile 

On every golden scale! 

## Second Verse
<!--Put the first five lines of a poem by Robert Frost in this section!-->
Such as we were we gave ourselves outright

(The deed of gift was many deeds of war)

To the land vaguely realizing westward,

But still unstoried, artless, unenhanced,

Such as she was, such as she would become.

## Third Verse
 <!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,

Shining with all his might:

He did his very best to make

The billows smooth and bright--

And this was odd, because it was

## Fourth Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Pretty women wonder where my secret lies.

I'm not cute or built to suit a fashion model's size

But when I start to tell them,

They think I'm telling lies.

I say,

It's in the reach of my arms

The span of my hips,

The stride of my step,

The curl of my lips.

I'm a woman

Phenomenally.

Phenomenal woman,

That's me.
